<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_self_study/blob/main/NumPy_Random_Numbers_%26_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pseudorandom Number Generation


In [2]:
import numpy as np

In [3]:
samples = np.random.standard_normal(size=(4,4))

In [4]:
samples

array([[-0.233132  ,  0.92703365, -0.35825713, -0.93113046],
       [ 1.52742827,  0.47950484, -0.10803013,  1.63462845],
       [ 1.11573799,  1.44619642, -0.39895167, -1.39111808],
       [-0.21866905, -0.53757879, -2.07152298, -0.46376467]])

In [5]:
from random import normalvariate

In [6]:
N =1_000_000

In [7]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

951 ms ± 320 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit np.random.standard_normal(N)

35.3 ms ± 543 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
rng = np.random.default_rng(seed=12345)

In [11]:
rng

Generator(PCG64) at 0x78F4D84A0D60

In [10]:
data = rng.standard_normal((2,3))

In [12]:
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [13]:
type(rng)

numpy.random._generator.Generator

#Universal Functions: Faast Element-Wise Array Functions


In [14]:
arr = np.arange(10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [18]:
x = rng.standard_normal(8)

In [19]:
y = rng.standard_normal(8)

In [20]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [21]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [22]:
np.maximum(x, y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [23]:
arr = rng.standard_normal(7) * 5

In [24]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [25]:
remainder, whole_part = np.modf(arr)

In [26]:
remainder

array([ 0.51459671, -0.10791367, -0.7909463 ,  0.24741966, -0.71800536,
       -0.40843795,  0.62369966])

In [27]:
whole_part

array([ 4., -8., -0.,  2., -6., -0.,  8.])

In [29]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [30]:
out = np.zeros_like(arr)

In [31]:
out

array([0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.add(arr, 1, out=out)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [33]:
out

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])