<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_self_study/blob/main/NumPy_Boolean_Arrays%2C_Sorting_%26_Set_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Methods for Boolean Arrays

In [1]:
import numpy as np

rng = np.random.default_rng()

In [2]:
arr = rng.standard_normal(100)

In [4]:
(arr > 0).sum() #Number of positive values

np.int64(44)

In [5]:
(arr <= 0).sum() #Number of non-positive values

np.int64(56)

In [7]:
bools = np.array([False, False, True, False])

In [8]:
bools.any()

np.True_

In [9]:
bools.all()

np.False_

In [10]:
#Sorting
arr = rng.standard_normal(6)
arr

array([-1.7224988 , -2.62850056, -0.69039637,  0.87883091,  0.17166166,
        1.16053855])

In [11]:
arr.sort()

In [12]:
arr

array([-2.62850056, -1.7224988 , -0.69039637,  0.17166166,  0.87883091,
        1.16053855])

In [14]:
arr = rng.standard_normal((5,3))

In [15]:
arr

array([[-0.18195577, -0.711173  ,  0.93694388],
       [-1.2444732 ,  0.52619378, -0.82161587],
       [-0.74394916, -0.32298337, -0.69418521],
       [ 0.56039555,  0.02799477, -0.04964215],
       [-0.65736809,  1.40802942, -1.53785745]])

In [16]:
arr.sort(axis=0)

In [17]:
arr

array([[-1.2444732 , -0.711173  , -1.53785745],
       [-0.74394916, -0.32298337, -0.82161587],
       [-0.65736809,  0.02799477, -0.69418521],
       [-0.18195577,  0.52619378, -0.04964215],
       [ 0.56039555,  1.40802942,  0.93694388]])

In [18]:
arr.sort(axis=1)

In [19]:
arr

array([[-1.53785745, -1.2444732 , -0.711173  ],
       [-0.82161587, -0.74394916, -0.32298337],
       [-0.69418521, -0.65736809,  0.02799477],
       [-0.18195577, -0.04964215,  0.52619378],
       [ 0.56039555,  0.93694388,  1.40802942]])

In [20]:
arr2 = np.array([5,-10,7,1,0,-3])

In [21]:
sorted_arr2 = np.sort(arr2)

In [22]:
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

##Unique and Other Set Logic

In [23]:
names = np.array(["Bob", "Will", "joe", "Bob","Will", "Joe", "Joe"])

In [24]:
np.unique(names)

array(['Bob', 'Joe', 'Will', 'joe'], dtype='<U4')

In [25]:
ints = np.array([3,3,3,2,2,1,1,4,4])

In [26]:
np.unique(ints)


array([1, 2, 3, 4])

In [27]:
sorted(set(names))


[np.str_('Bob'), np.str_('Joe'), np.str_('Will'), np.str_('joe')]

In [28]:
values = np.array([6,0,0,3,2,5,6])

In [29]:
np.in1d(values, [2,3,6])

/tmp/ipython-input-1269275309.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2,3,6])


array([ True, False, False,  True,  True, False,  True])