<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_self_study/blob/main/Numpyfull.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_arr = np.arange(1000000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
my_list = list(range(1_000_000))
#my_list

In [ ]:
%timeit my_arr2 = my_arr * 2

394 µs ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit my_list2 = [x * 2 for x in my_list]

30.6 ms ± 669 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#The Numpy ndarray:A Multidimensional Array Object

In [1]:
import numpy as np

In [2]:
data = np.array([[1.8, -0.3, 4], [0,-3,9.5]])

In [3]:
data

array([[ 1.8, -0.3,  4. ],
       [ 0. , -3. ,  9.5]])

##mathematical operations with data:

In [4]:
data * 10

array([[ 18.,  -3.,  40.],
       [  0., -30.,  95.]])

In [5]:
data + data

array([[ 3.6, -0.6,  8. ],
       [ 0. , -6. , 19. ]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

##Creating ndarrays

In [8]:
data1 = [6, 6.4, 7, 0, 2]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 6.4, 7. , 0. , 2. ])

In [11]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int64')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.empty((2,3,5))

array([[[4.71228194e-315, 0.00000000e+000, 2.12199579e-314,
         2.57409075e+151, 4.47543482e+217],
        [6.80648771e+199, 6.19406593e+223, 1.99108547e+209,
         3.76476751e-085, 1.14406376e+243],
        [5.03868116e+175, 1.53044312e-094, 4.12132803e-027,
         2.49963838e+233, 3.99461109e+252]],

       [[9.05280142e+223, 1.31470868e-320, 6.59737713e-310,
         6.59737815e-310, 5.37016946e-317],
        [6.59737811e-310, 6.59737811e-310, 6.59737713e-310,
         5.78916875e-317, 6.59737713e-310],
        [6.59737711e-310, 6.59737713e-310, 5.78926361e-317,
         6.59737713e-310, 6.59737713e-310]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##Data Types for ndarrays

In [22]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
arr = np.array([1,2,3,4,5])

In [26]:
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)

In [28]:
float_arr

array([1., 2., 3., 4., 5.])

In [29]:
float_arr.dtype

dtype('float64')

In [30]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [31]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [32]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [33]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)

In [34]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
int_array = np.arange(10)

In [36]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [37]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
zeros_unit32 = np.zeros(8, dtype="u4")

In [39]:
zeros_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

##Arithmetic with Numpy Arrays

In [40]:
arr = np.array([[1., 3., 5.], [6., 8., 10.]])

In [41]:
arr

array([[ 1.,  3.,  5.],
       [ 6.,  8., 10.]])

In [42]:
arr * arr

array([[  1.,   9.,  25.],
       [ 36.,  64., 100.]])

In [43]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
1 / arr

array([[1.        , 0.33333333, 0.2       ],
       [0.16666667, 0.125     , 0.1       ]])

In [45]:
arr / 2

array([[0.5, 1.5, 2.5],
       [3. , 4. , 5. ]])

In [46]:
arr ** 3

array([[   1.,   27.,  125.],
       [ 216.,  512., 1000.]])

In [47]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [48]:
arr

array([[ 1.,  3.,  5.],
       [ 6.,  8., 10.]])

In [49]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [50]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

##Basic Indexing and Slicing

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

np.int64(5)

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8] = 12

In [56]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [57]:
arr_slice = arr[5:8]

In [58]:
arr_slice

array([12, 12, 12])

In [59]:
arr_slice[1] = 12345

In [60]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [61]:
arr_slice[:] = 64

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [63]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

np.int64(3)

In [66]:
arr2d[0,2]

np.int64(3)

In [67]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [68]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
old_values = arr3d[0].copy()

In [71]:
arr3d[0] = 42

In [72]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[0] = old_values

In [74]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr3d[1,0]

array([7, 8, 9])

In [76]:
x = arr3d[1]

In [77]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [78]:
x[0]

array([7, 8, 9])

##Indexing with slices

In [79]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [80]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [81]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [88]:
lower_dim_slice = arr2d[1, :2]

In [91]:
lower_dim_slice.shape

(2,)

In [92]:
arr2d[:2, 2]

array([3, 6])

In [93]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [94]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [95]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Boolen Indexing

In [106]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [107]:
data = np.array([[4,7], [0,2], [-5, 6], [0,0], [1,2], [-12, -4], [3,4]])

In [108]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [109]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [110]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [111]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [112]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [113]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [114]:
data[names == "Bob", 1]

array([7, 0])

In [115]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [117]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [118]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [119]:
cond = names == "Bob"

In [120]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [121]:
mask = (names == "Bob") | (names == "Will")

In [122]:
mask

array([ True, False,  True,  True,  True, False, False])

In [124]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [125]:
data[data < 0] = 0

In [126]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [127]:
data[names != "Joe"] = 7

In [128]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

##Fancy Indexing

In [129]:
arr = np.zeros((8, 4))

In [131]:
for i in range(8):
  arr[i] = i

In [132]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [133]:
arr[[4,2,0,6]]

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [134]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [135]:
arr = np.arange(32).reshape((8, 4))

In [136]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [138]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [139]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [140]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [141]:
arr[[1,5,7,2], [0,3,1,2]] = 0

In [142]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

#Transposing Arrays and Swapping Axes

In [143]:
arr = np.arange(15).reshape((3,5))

In [144]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [145]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [147]:
arr = np.array([[0,1,0],[1,2,-2],[6,3,2],[-1,0,-1],[1,0,1]])

In [148]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [149]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [151]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [152]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [154]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])